name :  Test CI

on:
  push:
    branches:
      - 'feature/**'
      - main

jobs:
  QualityGateCheck:
    name: Quality Check
    runs-on: ubuntu-latest
    steps: 
      - name : Checkout Code
        uses : actions/checkout@v2
      - name : Static analysis with SonarCloud
        uses : sonarsource/sonarcloud-github-action@v1.3
        with:
          projectBaseDir: .
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.tests=tests/
        env :
          GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN : ${{secrets.SONAR_TOKEN}}         