name : Validate CodeBase

on:
  push:
    branches:
      - 'feature/**'
      - master

jobs:
  QualityGateCheck:
    name: Static Analysis 
    runs-on: ubuntu-latest
    steps: 
      - name : Checkout Code
      - uses : actions/checkout@v2
      - name : Static analysis with SonarCloud
        uses : sonarsource/sonarcloud-github-action@v1.3
        env :
          GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN : ${{secrets.SONAR_TOKEN}}

